name: drought
channels:
  - conda-forge
  - base
  - bioconda
  - R
dependencies:
  - r-base=4.1.3
  - r-tidyverse=1.3.2
  - r-rmarkdown=2.17
  - wget=1.20.3
  - snakemake=7.14.0
  - graphviz=5.0.1
  - coreutils>=9.1
